version: "3"
services:
  db:
    image: postgres:latest
    container_name: postgres_survey
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "survey"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./initdb/:/docker-entrypoint-initdb.d/
volumes:
  data:
